miniki:
  build: .
  links:
    - sling
  command: build deployBundle startBundle
  volumes_from:
    - miniki-gradle-cache
miniki-api:
  build: miniki-api
  volumes_from:
    - miniki-api-gradle-cache
whistlepost:
  image: micronode/whistlepost
  links:
    - sling
  command: build deployBundle startBundle
  volumes_from:
    - whistlepost-gradle-cache
sling:
  image: apachesling/sling
  mem_limit: 512m
  links:
    - "miniki-api:api"
  volumes:
    - "./sling.properties:/opt/sling/sling.properties"
  volumes_from:
    - sling-data
sling-data:
  image: tianon/true
  volumes:
    - /opt/sling/sling
haproxy:
  image: tutum/haproxy
  links:
    - sling
  ports:
    - "80:80"
    - "1936:1936"
  mem_limit: 128m
miniki-gradle-cache:
  image: cogniteev/echo:latest
  volumes:
    - /root/.gradle
miniki-api-gradle-cache:
  image: cogniteev/echo:latest
  volumes:
    - /root/.gradle
whistlepost-gradle-cache:
  image: cogniteev/echo:latest
  volumes:
    - /root/.gradle
